# The entire pipeline was shamelessy borrowed from https://github.com/NabuCasa/silabs-firmware-builder
# Kudos to NabuCasa and Stefan

name: Application and bootload builder

on:
  workflow_call:
    inputs:
      sdk_version:
        required: true
        type: string

      device:
        description: Device Part Name
        required: true
        type: string

      components:
        description: extra components to add to the project, comma separated
        required: true
        type: string

      configuration:
        description: extra configuration to add to the project, comma separated
        required: false
        type: string

      build_btl:
        description: "Build Bootloader"
        required: false
        default: false
        type: boolean

      image_name:
        required: false
        type: string
        default: "ghcr.io/${{ github.repository_owner }}/silabs-project-builder:${{ inputs.sdk_version }}"

      app_ota_string:
        required: false
        type: string
        default: Raz-1 Just a Light

      btl_version:
        required: true
        type: string

      flavor:
        required: true
        type: string


jobs:
  app-firmware-build-bootloader:
    if: inputs.build_btl
    name: Zigbee MLight App with Bootloader
    needs: bootloader-build
    strategy:
      fail-fast: false
      matrix:
        include:
          - name_suffix: debug

          - name_suffix: sed
            without: >-
              debug_swo
            configuration: >-
              SLI_ZIGBEE_PRIMARY_NETWORK_DEVICE_TYPE:SLI_ZIGBEE_NETWORK_DEVICE_TYPE_SLEEPY_END_DEVICE,
              SL_ZIGBEE_DEBUG_STACK_GROUP_RUNTIME_DEFAULT:0,
              SL_ZIGBEE_DEBUG_CORE_GROUP_RUNTIME_DEFAULT:0,
              SL_ZIGBEE_DEBUG_APP_GROUP_RUNTIME_DEFAULT:0,
              SL_ZIGBEE_DEBUG_ZCL_GROUP_RUNTIME_DEFAULT:0

          - name_suffix: end-device
            without: >-
              debug_swo
            configuration: >-
              SLI_ZIGBEE_PRIMARY_NETWORK_DEVICE_TYPE:SLI_ZIGBEE_NETWORK_DEVICE_TYPE_END_DEVICE,
              SL_ZIGBEE_DEBUG_STACK_GROUP_RUNTIME_DEFAULT:0,
              SL_ZIGBEE_DEBUG_CORE_GROUP_RUNTIME_DEFAULT:0,
              SL_ZIGBEE_DEBUG_APP_GROUP_RUNTIME_DEFAULT:0,
              SL_ZIGBEE_DEBUG_ZCL_GROUP_RUNTIME_DEFAULT:0

    uses: zha-ng/workflows-silabs/.github/workflows/slc-project-builder.yaml@v1
    with:
      image_name: ${{ inputs.image_name }}
      src_project: MLight
      project_name: MLight-${{ inputs.flavor }}-${{ matrix.name_suffix }}
      device: ${{ inputs.device }}
      components: ${{ inputs.components }}
      configuration: >-
        ${{ inputs.configuration != '' && format('{0},', inputs.configuration) || '' }}
        ${{ matrix.configuration != '' && format('{0},', matrix.configuration) || '' }}
        SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:32
      remove_components: ${{ matrix.without }}
      extra_c_defs: ""
      sdk_version: ${{ inputs.sdk_version }}
      metadata_extra: "{}"
      ota_string: ${{ inputs.app_ota_string }}
      sdk_extensions: >-
        "https://github.com/Adminiuga/Raz1_custom_components_extension"
      with_bootloader: ${{ needs.bootloader-build.outputs.project_name }}

  app-firmware-build:
    if: ${{ !inputs.build_btl }}
    name: Zigbee MLight App (no bootloader)
    strategy:
      fail-fast: false
      matrix:
        include:
          - name_suffix: debug

          - name_suffix: sed
            without: >-
              debug_swo
            configuration: >-
              SLI_ZIGBEE_PRIMARY_NETWORK_DEVICE_TYPE:SLI_ZIGBEE_NETWORK_DEVICE_TYPE_SLEEPY_END_DEVICE,
              SL_ZIGBEE_DEBUG_STACK_GROUP_ENABLED:0,
              SL_ZIGBEE_DEBUG_CORE_GROUP_ENABLED:0,
              SL_ZIGBEE_DEBUG_APP_GROUP_ENABLED:1,
              SL_ZIGBEE_DEBUG_ZCL_GROUP_ENABLED:0

          - name_suffix: end-device
            without: >-
              debug_swo
            configuration: >-
              SLI_ZIGBEE_PRIMARY_NETWORK_DEVICE_TYPE:SLI_ZIGBEE_NETWORK_DEVICE_TYPE_END_DEVICE,
              SL_ZIGBEE_DEBUG_STACK_GROUP_ENABLED:0,
              SL_ZIGBEE_DEBUG_CORE_GROUP_ENABLED:0,
              SL_ZIGBEE_DEBUG_APP_GROUP_ENABLED:1,
              SL_ZIGBEE_DEBUG_ZCL_GROUP_ENABLED:0

    uses: zha-ng/workflows-silabs/.github/workflows/slc-project-builder.yaml@v1
    with:
      image_name: ${{ inputs.image_name }}
      src_project: MLight
      project_name: MLight-${{ inputs.flavor }}-${{ matrix.name_suffix }}
      device: ${{ inputs.device }}
      components: ${{ inputs.components }}
      configuration: >-
        ${{ inputs.configuration != '' && format('{0},', inputs.configuration) || '' }}
        ${{ matrix.configuration != '' && format('{0},', matrix.configuration) || '' }}
        SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:32
      remove_components: ${{ matrix.without }}
      extra_c_defs: ""
      sdk_version: ${{ inputs.sdk_version }}
      metadata_extra: "{}"
      ota_string: ${{ inputs.app_ota_string }}
      sdk_extensions: >-
        "https://github.com/Adminiuga/Raz1_custom_components_extension"

  bootloader-build:
    if: inputs.build_btl
    name: Application bootloader
    uses: zha-ng/workflows-silabs/.github/workflows/slc-project-builder.yaml@v1
    with:
      image_name: ${{ inputs.image_name }}
      src_project: >-
        ${{ vars.btl_project_name != ''
            && vars.btl_project_name
            || 'bootloader-storage-internal-single-lzma'
        }}
      src_project_path: >-
        ${{
          vars.btl_template_path != ''
          && vars.btl_template_path
          || ( startsWith(inputs.device, 'EFR32MG1')
               && '/gecko_sdk/platform/bootloader/sample-apps/Series-1'
               || '/gecko_sdk/platform/bootloader/sample-apps/Series-2'
              )
        }}

      project_name: "MLight_btl-${{ inputs.flavor }}"
      device: ${{ inputs.device }}
      components: >-
        ${{ startsWith( inputs.device, 'EFR32MG12P') && 'brd4166a' || '' }},
        bootloader_compression_lzma
      configuration: >-
        ${{ inputs.configuration != '' && format('{0},', inputs.configuration) || '' }}
        BOOTLOADER_WRITE_DISABLE:1,
        BOOTLOADER_VERSION_MAIN_CUSTOMER:${{ inputs.btl_version }},
      extra_c_defs: ""
      sdk_version: ${{ inputs.sdk_version }}
      sdk_extensions: >-
        "https://github.com/Adminiuga/Raz1_custom_components_extension"
      sdkpatchpath: ''
      metadata_extra: "{}"
