# The entire pipeline was shamelessy borrowed from https://github.com/NabuCasa/silabs-firmware-builder
# Kudos to NabuCasa and Stefan

name: Silicon Labs builder

on:
  workflow_dispatch:
    inputs:
      build_btl:
        description: "Build Bootloader"
        required: false
        default: false
        type: boolean

  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
      - .github/workflows/app-btl-build.yaml
      - .github/workflows/silabs-project-builder.yaml
      - 'MLight/**'
      - 'patches/**'
    branches:
      - main
      - dev
      - 'rc-*'
    tags:
      - '*'

  pull_request:
    types: [opened, reopened, synchronize]


jobs:
  build-container:
    name: Create build container image
    permissions:
      packages: write
      contents: write
    uses: zha-ng/workflows-silabs/.github/workflows/build-gsdk-container.yaml@dev
    with:
      sdk_version: "4.4.5"
      gcc_version: 12.3.rel1
      zap_version: v2024.12.13


  app-btl-build:
    name: Zigbee MGM210 HAT App
    needs: build-container
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: EFR32MG12P332F1024GL125
            components: >-
              custom_tb2;raz1_custom_components,
              mx25_flash_shutdown_usart
            flavor: TBS2
            configuration: >-
              EMBER_AF_PLUGIN_OTA_CLIENT_POLICY_IMAGE_TYPE_ID:2287
          - device: MGM210LA22JIF
            components: >-
              brd_mgm210_expansion;raz1_custom_components,
            flavor: MGM210
          - device: brd4181b
            flavor: brd4181b
            configuration: >-
              EMBER_AF_PLUGIN_OTA_CLIENT_POLICY_IMAGE_TYPE_ID:2288
    uses: ./.github/workflows/app-btl-build.yaml
    with:
      sdk_version: ${{ needs.build-container.outputs.sdk_version }}
      device: ${{ matrix.device }}
      components: ${{ matrix.components }}
      build_btl: ${{ github.event.inputs.build_btl != '' && inputs.build_btl || startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/rc') || false }}
      image_name: ${{ needs.build-container.outputs.image_name }}
      btl_version: ${{ vars.btl_version != '' && vars.btl_version || '2' }}
      flavor: ${{ matrix.flavor }}
      configuration: ${{ matrix.configuration }}

